/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_beneth_HelloNative */

#ifndef _Included_fr_beneth_HelloNative
#define _Included_fr_beneth_HelloNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fr_beneth_HelloNative
 * Method:    helloNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_fr_beneth_HelloNative_helloNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
